export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#99ff33',
    accentRed: '#33cc33',
    accentPink: '#F96165',
    darkgreen:'#33cc33',
    lightgreen:'#99ff33',
    red:'#FB5D2E',
    pink:'#FFC231',
  };
  
  export const Categories = [
    {
      name: 'Burger',
      image: require('../Assets/Images/burger.png'),
      items: [
        {
          name: 'Classic Burger',
          weight: 120,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../Assets/Images/classicburger.png'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
          ingredients: [
            require('../Assets/Images/flour.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/Sliced.png'),
            require('../Assets/Images/Tomato.png'),
          ],
        },
        {
          name: 'Tikki Burger',
          weight: 150,
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/alootikkiburger.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
          ingredients: [
            require('../Assets/Images/Sliced.png'),
            require('../Assets/Images/Tomato.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/flour.png'),
          ],
        },
        {
          name: 'Biggie Cheese',
          weight: 250,
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/biggiecheese.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
          ingredients: [
            require('../Assets/Images/Tomato.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/Sliced.png'),
            require('../Assets/Images/flour.png'),
          ],
        },
      ],
    },
    {
      name: 'Pizza',
      image: require('../Assets/Images/pizza.png'),
      items: [
        {
          name: 'Pepperoni',
          weight: 250,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../Assets/Images/pizza2.png'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
          ingredients: [
            require('../Assets/Images/Tomato.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/Sliced.png'),
            require('../Assets/Images/flour.png'),
          ],
        },
        {
          name: ' Cheese Pizza',
          weight: 300,
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/pizza3.png'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
          ingredients: [
            require('../Assets/Images/Sliced.png'),
            require('../Assets/Images/flour.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/Tomato.png'),
          ],
        },
        {
          name: 'Mexican Green',
          weight: 350,
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/mexicangreenwave.png'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
          ingredients: [
            require('../Assets/Images/flour.png'),
            require('../Assets/Images/cheese.png'),
            require('../Assets/Images/Tomato.png'),
            require('../Assets/Images/Sliced.png'),
          ],
        },
      ],
    },
    {
      name: 'Soft Drinks',
      image: require('../Assets/Images/softdrinks.png'),
      items: [
        {
          name: 'Coco Cola',
          weight: 200,
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('../Assets/Images/cocacola.png'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
          ingredients: [require('../Assets/Images/cocacola.png')],
        },
        {
          name: 'Orange Juice',
          weight: 500,
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/orange.png'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          ingredients: [require('../Assets/Images/orange.png')],
        },
        {
          name: 'Mango Juice',
          weight: 150,
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../Assets/Images/mango.png'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
          ingredients: [require('../Assets/Images/mango.png')],
        },
      ],
    },
  ];